server {
    server_name clubpilatesanjuan.com.ar www.clubpilatesanjuan.com.ar 23.21.146.96; # Reemplaza con tu dominio/IP

    # 6.1. Servir archivos estáticos directamente (CSS, JS, Imágenes)
    # Apunta directamente a la carpeta 'static' dentro de /root/AuraPilates
    location /static {
        alias /root/AuraPilates/static;
    }

    # 6.2. Pasar todas las demás peticiones a Gunicorn
    location / {
        proxy_pass http://127.0.0.1:8000; # Gunicorn correrá en el puerto 8000
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/aurapilates.duckdns.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/aurapilates.duckdns.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = clubpilatesanjuan.com.ar www.clubpilatesanjuan.com.ar) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name clubpilatesanjuan.com.ar www.clubpilatesanjuan.com.ar 23.21.146.96;
    return 404; # managed by Certbot


}
